schema_version = "1.0.0"

id = "jurajis_daz_materials_to_blender"
name = "Juraji's DAZ Materials to Blender"
version = "1.0.0"
tagline = "Another DAZ-Blender bridge. But this time the user is in control!"
type = "add-on"

maintainer = "Juraji <github@juraji.nl>"
website = "https://github.com/Juraji/daz-materials-to-blender"
tags = ["Import-Export", "Material", "Shader", "Texturing", "UI", "Utility"]

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

[build]
paths_exclude_pattern = [
    "/.git/",
    "__pycache__/",
    ".*",
]