from .shader_group_converter import ShaderGroupConverter
from ..shaders import IrayUberShaderGroupApplier, IWaveTranslucentFabricShaderGroupApplier


class IrayUberToIWaveFabricShaderConverter(ShaderGroupConverter):
    from_type = IrayUberShaderGroupApplier
    to_type = IWaveTranslucentFabricShaderGroupApplier
    display_name = "Iray Uber To IWave Translucent Fabric"

    @classmethod
    def property_mapping(cls) -> list[tuple[str, str]]:
        i = cls.from_type
        o = cls.to_type

        return [
            (i.IN_DIFFUSE, o.IN_DIFFUSE),
            (i.IN_DIFFUSE_MAP, o.IN_DIFFUSE_MAP),

            (i.IN_NORMAL, o.IN_BASE_NORMAL),
            (i.IN_NORMAL_MAP, o.IN_BASE_NORMAL_MAP),
            (i.IN_BUMP_STRENGTH, o.IN_BASE_BUMP),
            (i.IN_BUMP_STRENGTH_MAP, o.IN_BASE_BUMP_MAP),

            (i.IN_DIFFUSE_OVERLAY_WEIGHT, o.IN_FIBER_LAYER_WEIGHT),
            (i.IN_DIFFUSE_OVERLAY_WEIGHT_MAP, o.IN_FIBER_LAYER_WEIGHT_MAP),
            (i.IN_DIFFUSE_OVERLAY_COLOR, o.IN_FIBER_LAYER_COLOR),
            (i.IN_DIFFUSE_OVERLAY_COLOR_MAP, o.IN_FIBER_LAYER_COLOR_MAP),
            (i.IN_DIFFUSE_OVERLAY_ROUGHNESS, o.IN_FIBER_LAYER_ROUGHNESS),
            (i.IN_DIFFUSE_OVERLAY_ROUGHNESS_MAP, o.IN_FIBER_LAYER_ROUGHNESS_MAP),

            (i.IN_CUTOUT_OPACITY, o.IN_CUTOUT_OPACITY),
            (i.IN_CUTOUT_OPACITY_MAP, o.IN_CUTOUT_OPACITY_MAP),
            (i.IN_DISPLACEMENT_STRENGTH, o.IN_DISPLACEMENT_STRENGTH),
            (i.IN_DISPLACEMENT_STRENGTH_MAP, o.IN_DISPLACEMENT_STRENGTH_MAP),
            (i.IN_MINIMUM_DISPLACEMENT, o.IN_MINIMUM_DISPLACEMENT),
            (i.IN_MAXIMUM_DISPLACEMENT, o.IN_MAXIMUM_DISPLACEMENT),

            (i.IN_GLOSSY_WEIGHT, o.IN_GLOSSY_LAYERED_WEIGHT),
            (i.IN_GLOSSY_WEIGHT_MAP, o.IN_GLOSSY_LAYERED_WEIGHT_MAP),
            (i.IN_GLOSSY_COLOR, o.IN_GLOSSY_COLOR),
            (i.IN_GLOSSY_COLOR_MAP, o.IN_GLOSSY_COLOR_MAP),
            (i.IN_GLOSSY_REFLECTIVITY, o.IN_GLOSSY_REFLECTIVITY),
            (i.IN_GLOSSY_REFLECTIVITY_MAP, o.IN_GLOSSY_REFLECTIVITY_MAP),
            (i.IN_GLOSSY_ROUGHNESS, o.IN_GLOSSY_ROUGHNESS),
            (i.IN_GLOSSY_ROUGHNESS_MAP, o.IN_GLOSSY_ROUGHNESS_MAP),

            (i.IN_DIFFUSE, o.IN_GRADIENT_LAYER_GRAZING_COLOR),
            (i.IN_DIFFUSE_MAP, o.IN_GRADIENT_LAYER_GRAZING_COLOR_MAP),
            (i.IN_DIFFUSE, o.IN_GRADIENT_LAYER_NORMAL_TINT),
            (i.IN_DIFFUSE_MAP, o.IN_GRADIENT_LAYER_NORMAL_TINT_MAP),

            (i.IN_METALLIC_FLAKES_WEIGHT, o.IN_METALLIC_FLAKES_WEIGHT),
            (i.IN_METALLIC_FLAKES_WEIGHT_MAP, o.IN_METALLIC_FLAKES_WEIGHT_MAP),
            (i.IN_METALLIC_FLAKES_COLOR, o.IN_METALLIC_FLAKES_COLOR),
            (i.IN_METALLIC_FLAKES_COLOR_MAP, o.IN_METALLIC_FLAKES_COLOR_MAP),
            (i.IN_METALLIC_FLAKES_ROUGHNESS, o.IN_METALLIC_FLAKES_ROUGHNESS),
            (i.IN_METALLIC_FLAKES_ROUGHNESS_MAP, o.IN_METALLIC_FLAKES_ROUGHNESS_MAP),
            (i.IN_METALLIC_FLAKES_SIZE, o.IN_METALLIC_FLAKES_SIZE),
            (i.IN_METALLIC_FLAKES_STRENGTH, o.IN_METALLIC_FLAKES_STRENGTH),
            (i.IN_METALLIC_FLAKES_DENSITY, o.IN_METALLIC_FLAKES_DENSITY),

            (i.IN_TOP_COAT_WEIGHT, o.IN_TOP_COAT_WEIGHT),
            (i.IN_TOP_COAT_WEIGHT_MAP, o.IN_TOP_COAT_WEIGHT_MAP),
            (i.IN_TOP_COAT_COLOR, o.IN_TOP_COAT_COLOR),
            (i.IN_TOP_COAT_COLOR_MAP, o.IN_TOP_COAT_COLOR_MAP),
            (i.IN_TOP_COAT_ROUGHNESS, o.IN_TOP_COAT_ROUGHNESS),
            (i.IN_TOP_COAT_ROUGHNESS_MAP, o.IN_TOP_COAT_ROUGHNESS_MAP),

            (i.IN_THIN_FILM_WEIGHT, o.IN_THIN_FILM_WEIGHT),
            (i.IN_THIN_FILM_ROTATIONS, o.IN_THIN_FILM_ROTATIONS),
            (i.IN_THIN_FILM_THICKNESS, o.IN_THIN_FILM_THICKNESS),
            (i.IN_THIN_FILM_THICKNESS_MAP, o.IN_THIN_FILM_THICKNESS_MAP),
            (i.IN_THIN_FILM_IOR, o.IN_THIN_FILM_IOR),
            (i.IN_THIN_FILM_IOR_MAP, o.IN_THIN_FILM_IOR_MAP),
        ]
